### ISSUE TITLE
when login gets success then how should i link my index.py application

### ISSUE THREAD

**Issue by bediljan** [Running-VincentW/Python-Tkinter-Login#1]
Hello Dear,

I want to use your login and signup form for my application. when the login gets success then how should link my main.py of application?

kindly help me

thank you very much for your assistance and cooperationi.

kindly email me: omarfarshadjee@gmail.com

**Comment by Running-VincentW** [comment]
Hi! I just took a look at the code and i think you should look at the function login_success. Currently upon a successful login it would show self.controller.show_frame("mainUI"), but you could replace it with whatever you want, or edit the mainUI to include your main program. Hope it helps.
```
def login_success(self):
        self.lbl_status.set("Login succeed.")
        self.controller.user = client(self.user_id)
        self.controller.show_frame("mainUI")
```
